// landing page /public/CommunityDirectory.jsx
import { useEffect, useMemo, useState } from 'react';
import { api } from '../../api/client.js';
import PublicHeader, { PublicFooter } from '../../components/PublicHeader.jsx';
import PublicBackdrop from '../../components/PublicBackdrop.jsx';
import PageHero, { accentFor } from '../../components/PageHero.jsx';
import EntityCard from '../../components/EntityCard.jsx';
import { LoadingState, EmptyState } from '../../components/PublicState.jsx';
import { UsersIcon, MapPinIcon, SearchIcon } from '../../components/icons.jsx';
import { SECTOR_TAXONOMY } from '../../constants.js';
import { PUBLIC_HERO_IMAGES } from '../../data/repositoryImages.js';

const PROVINCE_TYPES = ['Province', 'ViceProvince', 'Delegation'];
const PAGE_SIZE = 60;

export default function CommunityDirectory() {
  const [loading, setLoading] = useState(true);
  const [communities, setCommunities] = useState([]);
  const [provinces, setProvinces] = useState([]);
  const [provinceFilter, setProvinceFilter] = useState('');
  const [countryFilter, setCountryFilter] = useState('');
  const [sectorFilter, setSectorFilter] = useState('');
  const [search, setSearch] = useState('');
  const [sectorIndex, setSectorIndex] = useState(null);
  const [sectorLoading, setSectorLoading] = useState(false);
  const [visible, setVisible] = useState(PAGE_SIZE);

  useEffect(() => {
    let cancelled = false;
    setLoading(true);
    Promise.all([
      api.get('/org-units?type=Community&limit=3000'),
      ...PROVINCE_TYPES.map((type) => api.get(`/org-units?type=${type}&limit=300`)),
    ]).then(([communityRows, provinceRows, viceProvinceRows, delegationRows]) => {
      if (cancelled) return;
      setCommunities(communityRows);
      setProvinces([...provinceRows, ...viceProvinceRows, ...delegationRows].sort((a, b) => a.name.localeCompare(b.name)));
    }).finally(() => { if (!cancelled) setLoading(false); });
    return () => { cancelled = true; };
  }, []);

  useEffect(() => {
    if (!sectorFilter || sectorIndex) return;
    setSectorLoading(true);
    api.get('/org-units?type=Sector&limit=4000').then((rows) => {
      const idx = {};
      for (const inst of rows) {
        if (!inst.parent_id || !inst.institution_subtype) continue;
        if (!idx[inst.parent_id]) idx[inst.parent_id] = new Set();
        idx[inst.parent_id].add(inst.institution_subtype);
      }
      setSectorIndex(idx);
    }).finally(() => setSectorLoading(false));
  }, [sectorFilter, sectorIndex]);

  const countryOptions = useMemo(() => [...new Set(communities.map((c) => c.nation).filter(Boolean))].sort(), [communities]);
  const provincesRepresented = useMemo(() => new Set(communities.map((c) => c.parent_id).filter(Boolean)).size, [communities]);

  const filtered = useMemo(() => {
    return communities.filter((c) => {
      if (provinceFilter && String(c.parent_id) !== provinceFilter) return false;
      if (countryFilter && c.nation !== countryFilter) return false;
      if (sectorFilter && !(sectorIndex?.[c.id]?.has(sectorFilter))) return false;
      if (search && !c.name.toLowerCase().includes(search.toLowerCase())) return false;
      return true;
    });
  }, [communities, provinceFilter, countryFilter, sectorFilter, sectorIndex, search]);

  useEffect(() => { setVisible(PAGE_SIZE); }, [provinceFilter, countryFilter, sectorFilter, search]);

  return (
    <div className="relative min-h-screen bg-slate-50">
      <PublicBackdrop />
      <div className="relative z-10">
        <PublicHeader />

        <PageHero
          eyebrow="Registry"
          title="Community Directory"
          description="Every Community across the global Salesian registry — search by name or narrow down by Province, country and sector type."
          icon={UsersIcon}
          gradient={accentFor(0)}
          image={PUBLIC_HERO_IMAGES.communities}
          stats={!loading ? [
            { value: communities.length.toLocaleString(), label: 'Communities' },
            { value: provincesRepresented, label: 'Provinces' },
            { value: countryOptions.length, label: 'Countries' },
          ] : undefined}
        />

        <main className="w-full px-4 md:px-8 xl:px-12 py-12">
          <div className="mb-6 flex flex-wrap items-center gap-3 rounded-2xl border border-brand-100 bg-white/90 p-4 shadow-sm backdrop-blur-sm">
            <div className="relative flex-1 min-w-[200px]">
              <SearchIcon size={15} className="pointer-events-none absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" />
              <input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Search by community name…"
                className="w-full rounded-lg border border-slate-300 py-2 pl-9 pr-3 text-sm focus:border-brand-500 focus:outline-none focus:ring-1 focus:ring-brand-500" />
            </div>
            <select value={provinceFilter} onChange={(e) => setProvinceFilter(e.target.value)} className="rounded-lg border border-slate-300 px-3 py-2 text-sm text-slate-700 focus:border-brand-500 focus:outline-none">
              <option value="">All Provinces</option>
              {provinces.map((p) => <option key={p.id} value={p.id}>{p.name}</option>)}
            </select>
            <select value={countryFilter} onChange={(e) => setCountryFilter(e.target.value)} className="rounded-lg border border-slate-300 px-3 py-2 text-sm text-slate-700 focus:border-brand-500 focus:outline-none">
              <option value="">All Countries</option>
              {countryOptions.map((c) => <option key={c} value={c}>{c}</option>)}
            </select>
            <select value={sectorFilter} onChange={(e) => setSectorFilter(e.target.value)} className="rounded-lg border border-slate-300 px-3 py-2 text-sm text-slate-700 focus:border-brand-500 focus:outline-none">
              <option value="">All Sector Types</option>
              {SECTOR_TAXONOMY.map((s) => <option key={s} value={s}>{s}</option>)}
            </select>
          </div>

          {loading && <LoadingState label="Loading communities…" />}
          {sectorFilter && sectorLoading && <div className="mb-4 text-xs text-slate-500">Loading sector data…</div>}
          {!loading && filtered.length === 0 && (
            <EmptyState icon={UsersIcon} title="No communities match your filters" message="Try clearing the search or filters above." />
          )}
          {!loading && filtered.length > 0 && (
            <>
              <div className="mb-3 text-xs font-medium text-slate-500">{filtered.length} of {communities.length} communities{filtered.length > visible ? ` — showing first ${visible}` : ''}</div>
              <div className="grid gap-3 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 xl:grid-cols-5">
                {filtered.slice(0, visible).map((c, idx) => (
                  <EntityCard
                    key={c.id}
                    to={`/communities/${c.id}`}
                    icon={UsersIcon}
                    gradient={accentFor(idx)}
                    title={c.name}
                    dense
                    meta={(
                      <span className="flex items-center gap-1"><MapPinIcon size={12} /> {c.city || '—'}{c.nation ? `, ${c.nation}` : ''}</span>
                    )}
                  />
                ))}
              </div>
              {filtered.length > visible && (
                <div className="mt-8 text-center">
                  <button onClick={() => setVisible((v) => v + PAGE_SIZE)} className="rounded-lg border border-slate-300 bg-white px-5 py-2 text-sm font-semibold text-slate-700 shadow-sm transition hover:border-brand-300 hover:bg-slate-50">
                    Show more
                  </button>
                </div>
              )}
            </>
          )}
        </main>
        <PublicFooter />
      </div>
    </div>
  );
}

// gsdp-ui/src/views/public/CommunityDirectory.vue
<template>
  <div class="relative min-h-screen bg-slate-50">
    <PublicHeader />

    <PageHero
      eyebrow="Registry"
      title="Community Directory"
      description="Every Community across the global Salesian registry — search by name or narrow down by Province, country and sector type."
      icon="Users"
      :stats="!loading ? [
        { value: communities.length.toLocaleString(), label: 'Communities' },
        { value: provincesRepresented, label: 'Provinces' },
        { value: countryOptions.length, label: 'Countries' },
      ] : null"
    />

    <main class="w-full px-4 md:px-8 xl:px-12 py-12">
      <div class="mb-6 flex flex-wrap items-center gap-3 rounded-2xl border border-brand-100 bg-white/90 p-4 shadow-sm">
        <div class="relative flex-1 min-w-[200px]">
          <Icon name="Search" :size="15" class="pointer-events-none absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" />
          <input v-model="search" placeholder="Search by community name…"
            class="w-full rounded-lg border border-slate-300 py-2 pl-9 pr-3 text-sm focus:border-brand-500 focus:outline-none focus:ring-1 focus:ring-brand-500" />
        </div>
        <select v-model="provinceFilter" class="rounded-lg border border-slate-300 px-3 py-2 text-sm text-slate-700 focus:border-brand-500 focus:outline-none">
          <option value="">All Provinces</option>
          <option v-for="p in provinces" :key="p.name" :value="p.name">{{ p.canonical_name }}</option>
        </select>
        <select v-model="countryFilter" class="rounded-lg border border-slate-300 px-3 py-2 text-sm text-slate-700 focus:border-brand-500 focus:outline-none">
          <option value="">All Countries</option>
          <option v-for="c in countryOptions" :key="c.name" :value="c.name">{{ c.country_name }}</option>
        </select>
        <select v-model="sectorFilter" class="rounded-lg border border-slate-300 px-3 py-2 text-sm text-slate-700 focus:border-brand-500 focus:outline-none">
          <option value="">All Sector Types</option>
          <option v-for="s in categories" :key="s.name" :value="s.name">{{ s.category_name }}</option>
        </select>
      </div>

      <LoadingState v-if="loading" label="Loading communities…" />
      <div v-else-if="sectorFilter && sectorLoading" class="mb-4 text-xs text-slate-500">Loading sector data…</div>
      <EmptyState v-else-if="filtered.length === 0" icon="Users" title="No communities match your filters" message="Try clearing the search or filters above." />
      <template v-else>
        <div class="mb-3 text-xs font-medium text-slate-500">
          {{ filtered.length }} of {{ communities.length }} communities{{ filtered.length > visible ? ` — showing first ${visible}` : '' }}
        </div>
        <div class="grid grid-cols-1 gap-3 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 xl:grid-cols-5">
          <EntityCard v-for="(c, idx) in filtered.slice(0, visible)" :key="c.name" :to="`/communities/${c.name}`" icon="Users" :gradient="accentFor(idx)" :title="c.canonical_name" dense>
            <template #meta>
              <span class="flex items-center gap-1"><Icon name="MapPin" :size="12" /> {{ c.city || '—' }}</span>
            </template>
          </EntityCard>
        </div>
        <div v-if="filtered.length > visible" class="mt-8 text-center">
          <button @click="visible += PAGE_SIZE" class="rounded-lg border border-slate-300 bg-white px-5 py-2 text-sm font-semibold text-slate-700 shadow-sm transition hover:border-brand-300 hover:bg-slate-50">
            Show more
          </button>
        </div>
      </template>
    </main>
    <PublicFooter />
  </div>
</template>

<script setup>
import { computed, onMounted, ref, watch } from 'vue';
import PublicHeader from '@/components/public/PublicHeader.vue';
import PublicFooter from '@/components/public/PublicFooter.vue';
import PageHero from '@/components/public/PageHero.vue';
import { accentFor } from '@/components/public/PageHero.js';
import EntityCard from '@/components/public/EntityCard.vue';
import LoadingState from '@/components/public/LoadingState.vue';
import EmptyState from '@/components/public/EmptyState.vue';
import Icon from '@/components/icons/Icon.vue';
import { listActivityCategories, listCountries, listOrgUnits } from '@/api/registry.js';

const PAGE_SIZE = 60;

const loading = ref(true);
const communities = ref([]);
const provinces = ref([]);
const countryOptions = ref([]);
const categories = ref([]);
const provinceFilter = ref('');
const countryFilter = ref('');
const sectorFilter = ref('');
const search = ref('');
const visible = ref(PAGE_SIZE);

const sectorIndex = ref(null);
const sectorLoading = ref(false);

onMounted(async () => {
  try {
    const [communityRows, provinceRows, countries, cats] = await Promise.all([
      listOrgUnits({ doctype: 'Community', limit: 3000 }),
      listOrgUnits({ doctype: 'Province', limit: 500 }),
      listCountries(),
      listActivityCategories(),
    ]);
    communities.value = communityRows;
    provinces.value = [...provinceRows].sort((a, b) => a.canonical_name.localeCompare(b.canonical_name));
    countryOptions.value = countries;
    categories.value = cats;
  } finally {
    loading.value = false;
  }
});

watch(sectorFilter, async (val) => {
  if (!val || sectorIndex.value) return;
  sectorLoading.value = true;
  try {
    const activities = await listOrgUnits({ doctype: 'Activity', limit: 4000 });
    const idx = {};
    for (const a of activities) {
      if (!a.community || !a.activity_category) continue;
      if (!idx[a.community]) idx[a.community] = new Set();
      idx[a.community].add(a.activity_category);
    }
    sectorIndex.value = idx;
  } finally {
    sectorLoading.value = false;
  }
});

const provincesRepresented = computed(() => new Set(communities.value.map((c) => c.province).filter(Boolean)).size);

const filtered = computed(() =>
  communities.value.filter((c) => {
    if (provinceFilter.value && c.province !== provinceFilter.value) return false;
    if (countryFilter.value && c.country !== countryFilter.value) return false;
    if (sectorFilter.value && !sectorIndex.value?.[c.name]?.has(sectorFilter.value)) return false;
    if (search.value && !c.canonical_name.toLowerCase().includes(search.value.toLowerCase())) return false;
    return true;
  })
);

watch([provinceFilter, countryFilter, sectorFilter, search], () => { visible.value = PAGE_SIZE; });
</script>
